pipeline:
  build:
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+signed_commit_check
    image: ukhomeoffice/drone-docker
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/signed-commit-check
    secrets: [ docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
    when:
      event: push

  build_tag:
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+signed_commit_check
    image: ukhomeoffice/drone-docker
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/signed-commit-check
    secrets: [ docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
