---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: signed-commit-ingress
spec:
  rules:
  - host: signed-commit-check.notprod.homeoffice.gov.uk
    http:
      paths:
      - backend:
          serviceName: signed-commit-check-service
          servicePort: http
        path: /